###
# installs packages specific to the database server. this configuration
# runs PostgreSQL
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes 

- name: ensure postgresql database packages are installed
  apt: name={{item}}
  sudo: yes 
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
