---
# this playbook contains common plays that will be run on all nodes.

- name: ensure apt cache is up to date
  apt: update_cache=yes 
  sudo: yes
  
- name: install fail2ban for security purposes
  apt: pkg=fail2ban state=latest
  sudo: yes
